service: s3-image-upload

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY